# Generated by Django 4.1.1 on 2022-09-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_item_stripe_price_id_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stripe_price_id',
        ),
    ]
