# Generated by Django 4.1.1 on 2022-09-21 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_discount_discount_only_one_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='payments.item', verbose_name='На какой продукт скидка'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='absolute_discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Скидка в рублях'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent_discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Скидка в процентах'),
        ),
    ]
